spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_foundation?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: ai_app
    password: ${DB_PASSWORD:AiApp@2026}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
  ai:
    model:
      chat: openai
      embedding: openai
    openai:
      api-key: sk-0e4ac33162d44038ba556a5d0e084a13
      #base-url: http://localhost:11434
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-v4-pro
      embedding:
        options:
          model: bge-m3

logging:
  level:
    com.ai.foundation: DEBUG
